name: fingerpaint
summary: Draw using your laptop's touchpad
version: '1.3.0'
grade: stable
confinement: strict
base: core22
license: GPL-2.0
icon: snap/gui/fingerpaint.svg
architectures:
  - amd64
  - arm64
donation:
  - "https://github.com/sponsors/Wazzaps"
  - "https://liberapay.com/wazzaps"
contact: "david.shlemayev@gmail.com"
issues: "https://github.com/Wazzaps/fingerpaint/issues"
website: "https://github.com/Wazzaps/fingerpaint"
source-code: "https://github.com/Wazzaps/fingerpaint"
title: Fingerpaint
description: |
  This utility lets you draw using your laptop's touchpad.
  Pressing any key or clicking the touchpad will finish the drawing.
  Your touchpad will not control the cursor while drawing, though external mice should still work.
  It has support for both X11 (all desktop environments), and Wayland (just Gnome at the moment).

apps:
  fingerpaint:
    command-chain:
      - bin/debian-multiarch-triplet-provider-launch
      - bin/tcltk-launch
    command: bin/fingerpaint
    plugs: [desktop, wayland, x11, hardware-observe, raw-input, gsettings]
    environment:
      PYTHONPATH: "$PYTHONPATH:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10:$SNAP/usr/lib/python3.10/lib-dynload"
      GI_TYPELIB_PATH: "$SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0"

parts:
  fingerpaint:
    plugin: python
    source: "."
    build-packages: [python3-tk, libglib2.0-bin, gsettings-desktop-schemas] 
    stage-packages: [python3-tk, python3-dbus, python3-gi, xinput, libglib2.0-bin, dconf-cli, gsettings-desktop-schemas]

  desktop-settings-build:
    plugin: nil
    after: [fingerpaint]
    build-packages: [libglib2.0-bin, gsettings-desktop-schemas] 
    stage-packages: [libglib2.0-bin, gsettings-desktop-schemas]
    override-prime: |
       set -eux
       snapcraftctl prime
       ls -l usr/share/glib-2.0/
       ls -l usr/share/glib-2.0/schemas
       glib-compile-schemas usr/share/glib-2.0/schemas
  
  debian-multiarch-triplet-provider-launch:
    plugin: nil
    stage-snaps:
      - debian-multiarch-triplet-provider-launch

  tcltk-launch:
    plugin: nil
    stage-snaps:
      - tcltk-launch   

layout:
  /usr/share/tcltk:
    bind: $SNAP/usr/share/tcltk
